/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import com.sun.glass.events.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TWD_D
 */
public class Venta extends javax.swing.JFrame implements Runnable{
     int N= 1, numeroClie = 0, CantidadTotal = 0;
     double total = 0;
     String hora, minutos,segundos,ampm;
     Calendar calendario;
     Thread h1;
     Calendar FechaVentas;
     SimpleDateFormat FechaFormato=new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
      DecimalFormat deci=new DecimalFormat("0.00");
    /**
     * Creates new form Venta
     */
     void habilitar(){
         AGREGAR.setEnabled(true);
     }
      
     public void run(){
       Thread ct = Thread.currentThread();
            while(ct == h1) {   
             calcular();
             lbHora.setText(hora + ":" + minutos + ":" + segundos + " "+ampm);
             try {
              Thread.sleep(1000);
             }catch(InterruptedException e) {}
            }
           }
                
     public void calcular(){
         Calendar calendario = new GregorianCalendar();
                Date fechaHoraActual = new Date();


                calendario.setTime(fechaHoraActual);
                ampm = calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";

                if(ampm.equals("PM")){
                 int h = calendario.get(Calendar.HOUR_OF_DAY)-12;
                 hora = h>9?""+h:"0"+h;
                }else{
                 hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);            
                }
                     
                minutos = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
                segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND); 
}
    public Venta() {
        initComponents();
        this.setLocationRelativeTo(null);
        TOTAL.setText("0");
        h1 = new Thread(this);
        h1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PONER = new javax.swing.JComboBox<>();
        BUSCAR = new javax.swing.JTextField();
        MOSTRAR = new javax.swing.JComboBox<>();
        AGREGAR = new javax.swing.JButton();
        BORRAR = new javax.swing.JButton();
        PAGAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TOTAL = new javax.swing.JTextField();
        RECIBI = new javax.swing.JTextField();
        CAMBIO = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        CALCULAR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        IVA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CANTIDAD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SUBTOTAL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        LIMPIAR = new javax.swing.JButton();
        GUARDAR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PUNTO DE VENTA");
        setBackground(new java.awt.Color(153, 255, 153));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "Código", "Descripción", "Nombre", "Marca", "Presentación", "Precio", "Cantidad", "Costo Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 830, 341));

        PONER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CODIGO", "MARCA" }));
        getContentPane().add(PONER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, 84, -1));

        BUSCAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BUSCARKeyPressed(evt);
            }
        });
        getContentPane().add(BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 22, 133, -1));

        getContentPane().add(MOSTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 22, 555, -1));

        AGREGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        AGREGAR.setEnabled(false);
        AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGARActionPerformed(evt);
            }
        });
        getContentPane().add(AGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 175, 80));

        BORRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        BORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRARActionPerformed(evt);
            }
        });
        getContentPane().add(BORRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 175, 80));

        PAGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/billete.png"))); // NOI18N
        PAGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAGARActionPerformed(evt);
            }
        });
        getContentPane().add(PAGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, 175, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("TOTAL A PAGAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 108, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("RECIBÍ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 108, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CAMBIO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 108, 24));
        getContentPane().add(TOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, 170, -1));
        getContentPane().add(RECIBI, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 170, -1));
        getContentPane().add(CAMBIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 175, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_volver.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 90, 60));

        jButton5.setText("SALIR");
        jButton5.setActionCommand("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, -1, -1));

        CALCULAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unnamed.png"))); // NOI18N
        CALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULARActionPerformed(evt);
            }
        });
        getContentPane().add(CALCULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, 180, 80));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("IVA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 100, -1));
        getContentPane().add(IVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 170, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CANTIDAD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 90, -1));

        CANTIDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANTIDADActionPerformed(evt);
            }
        });
        getContentPane().add(CANTIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("SUBTOTAL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 130, -1));
        getContentPane().add(SUBTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 170, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("LISTA DE PRODUCTOS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 320, -1));

        lbHora.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 280, 50));

        LIMPIAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/more_cleaner.png"))); // NOI18N
        LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPIARActionPerformed(evt);
            }
        });
        getContentPane().add(LIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 90, 60));

        GUARDAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });
        getContentPane().add(GUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 90, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo gris.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BUSCARKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BUSCARKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)//El metodo getKeyCode me fue mas ultil para poder usar la tecla enter
               //Según invetigué éste metodo es más bien usado en el evento, KeyReleased, pero en teoria debe de funcionar aquí tambien, ya que se está pulsando una tecla.
                MOSTRAR.removeAllItems();//Este metodo sirve para remover lo que contenga el segundo combobox cuando muestre los resultados de la busque que se 

         //hizo en el textField, para que cuando el usuario vuelva a realizar otra busqueda, no me acumule los resultados
               //jComboBox1.setSelectedIndex(1); Use está línea de codigo para indicar al usuario que es lo que tiene seleccionado, pero por
               //alguna razon no me corria, así que opté por guardar el metodo en una variable, para poder usarla en un case, ya que 
               //el usuario realizará la busqueda por dos opciones que son: "Marca" y "Codigo"
                int a = PONER.getSelectedIndex();
            switch(a)
            {     
                case 0:
                   try{
                       String temp = System.getProperty("user.dir")+"\\src\\Ventanas\\inventario.txt";
                       FileReader Ruta = new FileReader(temp);
                       BufferedReader Lector = new BufferedReader(Ruta);

                       String datos="";
                       while ((datos = Lector.readLine()) != null){
                            String [] Datos = datos.split("\\|");
                            if(Datos[0].equals(BUSCAR.getText()))
                                MOSTRAR.addItem(datos);
                       }
                       Lector.close();
                       break;
                   } catch (IOException ex) {
                 
                    JOptionPane.showMessageDialog(null,"Debe Teclear solo codigo","Advertencia",JOptionPane.ERROR_MESSAGE);
                       }
                 
                case 1: 
                      
                    try{
//                       FileReader Ruta = new FileReader("C:\\Users\\TWD_D\\OneDrive\\Documentos\\NetBeansProjects\\Punto_Venta\\src\\Ventanas\\inventario.txt");
//                       BufferedReader Lector = new BufferedReader(Ruta);
                       String temp = System.getProperty("user.dir")+"\\src\\Ventanas\\inventario.txt";
                       FileReader Ruta = new FileReader(temp);
                       BufferedReader Lector = new BufferedReader(Ruta);

                       String datos="";
                       while ((datos = Lector.readLine()) != null){
                            String [] Datos = datos.split("\\|");
                            if(Datos[4].equals(BUSCAR.getText()))
                                MOSTRAR.addItem(datos);
                       }
                       Lector.close();
                       break;
                   } catch (IOException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
    }//GEN-LAST:event_BUSCARKeyPressed

    private void AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGARActionPerformed
              MOSTRAR.getSelectedItem();
              DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
              //String [] info = {"N", "Código", "Descripción", "Marca", "Presentación", "Cantidad", "Precio", "Subtotal"};
              
              String datos;
              double can = Double.parseDouble(CANTIDAD.getText());
              if(can == 0){
                  JOptionPane.showMessageDialog(null,"Debe Teclear solo codigo","Advertencia",JOptionPane.ERROR_MESSAGE);
              }
              
              double sub;
//              
              
            

              while ((datos = MOSTRAR.getSelectedItem().toString()) != null){
                           
                           String [] Datos = datos.split("\\|");
                           sub = Double.parseDouble(Datos[6]) * can;
                           Object[] a = {N,Datos[0],Datos[2],Datos[3],Datos[4], Datos[5],Datos[6],can,sub};
                           modelo.addRow(a);
                           total= total+ sub;
                           String p = String.format("%6.2f", total);
                           SUBTOTAL.setText(p);
                           CantidadTotal++ ; 
//                          
                           
                           break;
                           
                     }
               N = N +1;
      
    }//GEN-LAST:event_AGREGARActionPerformed

    private void CALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULARActionPerformed
        double v = Double.parseDouble(SUBTOTAL.getText());
        double iva = v * .16;

        String iv = String.format("%6.2f", iva);
        IVA.setText(iv);
        double M = v + iva;
        String to = String.format("%6.2f", M);
        TOTAL.setText(to);      
    }//GEN-LAST:event_CALCULARActionPerformed

    private void PAGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAGARActionPerformed
         numeroClie = numeroClie++;
         double resta; 
         resta = Double.parseDouble(RECIBI.getText()) - Double.parseDouble(TOTAL.getText());
         String rest = String.format("%6.2f", resta);
         CAMBIO.setText(rest);
         
    }//GEN-LAST:event_PAGARActionPerformed

    private void BORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRARActionPerformed
         DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        double z = 0.0, subtotalAct = 0.0, costototal= 0.0;
        int FilaSele;
        int resp;
        int fil;
        try {
            FilaSele = jTable1.getSelectedRow();
            if(FilaSele == -1){
                JOptionPane.showMessageDialog(null,"Debe selecciona el producto a elimimar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }else{
                resp = JOptionPane.showConfirmDialog(null,"¿Esta seguro de eliminar este producto?", "Eliminar", JOptionPane.YES_NO_OPTION);
                if(resp == JOptionPane.YES_NO_OPTION){
                    costototal = Double.parseDouble(jTable1.getValueAt(FilaSele, 8).toString());
                    subtotalAct = Double.parseDouble(SUBTOTAL.getText())- costototal;
                    total = subtotalAct;
                    SUBTOTAL.setText(""+ total);
                    //fil = (int)modelo.getValueAt(FilaSele,0);
                    modelo.removeRow(FilaSele);
                    
                }
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"No se eliminó el producto seleccionado, verifique", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_BORRARActionPerformed

    private void LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPIARActionPerformed
        try {
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            int filas = jTable1.getRowCount();
            for(int i = 0; filas >i ; i++ ){
                modelo.removeRow(0);
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }//GEN-LAST:event_LIMPIARActionPerformed
    
    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
           int folioCli = (int)(Math.random()*9999+1); //PARA GENERAR NUMEROS ALEATORIOS, SERVIRAN PARA EL FOLIO DEL CLIENTE     
                    
    
         try{
                BufferedWriter escritor=new BufferedWriter(new FileWriter(new File("DetalleVenta.txt"), true));
                escritor.write("Cliente #"+numeroClie+"| "+FechaFormato.format(FechaVentas.getTime())+"| Folio del cliente #SSD"+folioCli+"| Importe total $"+deci.format(TOTAL)+"|"+CantidadTotal+" articulos vendidos.\n");
                escritor.newLine();
                escritor.close();
             }
              catch(Exception ex){
            
             }
          try{
                DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                BufferedWriter escritor2= new BufferedWriter(new FileWriter(new File("DatosVenta.txt"),true));
                escritor2.write("Venta #"+numeroClie+"| Folio de la venta #VSF"+folioCli);
                escritor2.newLine();
                            for(int i=0;i<modelo.getRowCount();i++){
                            String codigoO=modelo.getValueAt(i,1).toString();
                            String precioO=modelo.getValueAt(i, 6).toString();
                            String cantidadO=modelo.getValueAt(i, 7).toString();
                            escritor2.write("articulo #"+codigoO+"|"+"$"+precioO+"|"+cantidadO+" unidad(es)");
                            escritor2.newLine();
                        }
                        escritor2.close();
                        
              }
             
              catch(Exception ex){
              
              }
       
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        modelo=(javax.swing.table.DefaultTableModel)this.jTable1.getModel();
        PONER.setSelectedIndex(0);
        BUSCAR.setText(null);
        MOSTRAR.setSelectedIndex(-1);
        CANTIDAD.setText(null);
        SUBTOTAL.setText(null);
        IVA.setText(null);
        TOTAL.setText(null);
        RECIBI.setText(null);
        CAMBIO.setText(null);
        numeroClie = numeroClie++;
        
//         File archivoVenta = new File("Detalla venta.csv");
//        try {      
//                 FileWriter archivo = new FileWriter(archivoVenta);
//                 BufferedWriter esc = new BufferedWriter(archivo);
//
//                 String texto ="\n";
//                     for (int a=0; a<jTable1.getRowCount(); a++)
//                       for (int b=0; b<jTable1.getColumnCount(); b++){ 
//          
//                        texto +=(jTable1.getValueAt(a,b));
////                      texto += jTable1.getColumnName(b) + jTable1.getValueAt(a,b);
//                        esc.write(texto);
//                 }
//
//                 esc.close();// cierra flujo
//        } catch (Exception e) {
//        }
//        
    }//GEN-LAST:event_GUARDARActionPerformed

    private void CANTIDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANTIDADActionPerformed
        habilitar();
    }//GEN-LAST:event_CANTIDADActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR;
    private javax.swing.JButton BORRAR;
    private javax.swing.JTextField BUSCAR;
    private javax.swing.JButton CALCULAR;
    private javax.swing.JTextField CAMBIO;
    private javax.swing.JTextField CANTIDAD;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JTextField IVA;
    private javax.swing.JButton LIMPIAR;
    private javax.swing.JComboBox<String> MOSTRAR;
    private javax.swing.JButton PAGAR;
    private javax.swing.JComboBox<String> PONER;
    private javax.swing.JTextField RECIBI;
    private javax.swing.JTextField SUBTOTAL;
    private javax.swing.JTextField TOTAL;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbHora;
    // End of variables declaration//GEN-END:variables
}
